
name: media-mojo-portfolio
services:
- environment_slug: node-js
  github:
    branch: main
    deploy_on_push: true
    repo: YOUR_USERNAME/YOUR_REPO_NAME
  http_port: 8080
  build_command: npm install --force && npm run build
  run_command: node serve.js
  envs:
  - key: NODE_VERSION
    value: "18.x"
  - key: NODE_ENV
    value: "production"
