// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mfolmgigcagdvqxulzvh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1mb2xtZ2lnY2FnZHZxeHVsenZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNjE5ODAsImV4cCI6MjA2ODgzNzk4MH0.CFrM34GykFQ0JxN0WowIopA6znI8H2Tex6IIGPgSxiQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});