
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ahblaxqjcjuzirfbofge.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFoYmxheHFqY2p1emlyZmJvZmdlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwNDQwNjEsImV4cCI6MjA2MjYyMDA2MX0.IjWBvzshMH_LgmB_m35PC2aYtHJRH9c6KeBk0IgsSqw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
